@host = http://localhost:5118
@farmId = "5e1f5b9b-7b1f-4b1f-9b9b-7b1f4b1f9b9b"
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2NmMyMDgyYS00NWI0LTQ2YzUtODA0YS04ZmYxNmNjYjY2ZjMiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsIm5iZiI6MTY3NDUwMjgwMCwiZXhwIjoxNjc0NTA2NDAwLCJpYXQiOjE2NzQ1MDI4MDAsImlzcyI6IkFQSUJvaWxhcnBsYXRlIiwiYXVkIjoiQVBJQm9pbGFycGxhdGUifQ.OCzuy2UGAoWBHG9oXvpsOICTyKV7_DMyDIdUJbUjNsg
POST {{host}}/farms/{{farmId}}/cows
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "initialWeight": 100,
    "initialPrice": 1000,
    "onBoardingDate": "2020-01-01T00:00:00.000Z"    
}