@host = http://localhost:5118
@farmId = "5e1f5b9b-7b1f-4b1f-9b9b-7b1f4b1f9b9b"
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzMGNlMDdmZS1lNDBmLTQ2ODAtOTgyNy1hMGE5N2M3MTYwM2MiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsIm5iZiI6MTY3NDYzNjkyOSwiZXhwIjoxNjc0NjQwNTI5LCJpYXQiOjE2NzQ2MzY5MjksImlzcyI6IkFQSUJvaWxhcnBsYXRlIiwiYXVkIjoiQVBJQm9pbGFycGxhdGUifQ.l3bpCRv9dceT2y6MXb4oBRsARnNZngwo34S2NCrAojk
POST {{host}}/farms/{{farmId}}/cows
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "initialWeight": 100,
    "initialPrice": 1000,
    "onBoardingDate": "2020-01-01T00:00:00.000Z"    
}