@host = http://localhost:5118
@farmId = "5e1f5b9b-7b1f-4b1f-9b9b-7b1f4b1f9b9b"
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2MjQyMWVhZS1iZWQ3LTQwMjAtOGRiOS02ZTVjNjk2ZTQ3NzUiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsIm5iZiI6MTY3NDQyNDYwNywiZXhwIjoxNjc0NDI4MjA3LCJpYXQiOjE2NzQ0MjQ2MDcsImlzcyI6IkFQSUJvaWxhcnBsYXRlIiwiYXVkIjoiQVBJQm9pbGFycGxhdGUifQ.aW7fu2rom2CDqriwTRSYliMQ-X9zRr4ez4Hvfu9_c4U
POST {{host}}/farms/{{farmId}}/cows
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "initialWeight": 100,
    "initialPrice": 1000,
    "onBoardingDate": "2020-01-01T00:00:00.000Z"    
}